spring:
  application:
    name: notification-service
  profiles:
    active: dev
  config:
    import: "optional:nacos:cloudstorage-common.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml

server:
  port: 8083
